version: 2
updates:
  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    insecure-external-code-execution: allow
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: pyspark
      - dependency-name: pandas
        update-types:
          - version-update:semver-major
    groups:
      01_major-updates:
        patterns:
          - '*'
        update-types:
          - major
      02_minor-updates:
        patterns:
          - '*'
        update-types:
          - minor
      03_patch-updates:
        patterns:
          - '*'
        update-types:
          - patch
