fail_fast: false
default_stages: [commit]

repos:
  # ============================================================================
  # General checks
  # ============================================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [commit, manual]
      - id: end-of-file-fixer
        stages: [commit, manual]
      - id: check-yaml
        stages: [commit, manual]
      - id: check-added-large-files
        stages: [commit, manual]
      - id: check-docstring-first
        files: \.py$
        stages: [commit, manual]
      - id: check-merge-conflict
        stages: [commit, manual]
      - id: check-case-conflict
        stages: [commit, manual]

  # ============================================================================
  # Ruff - Modern Python linter and formatter
  # ============================================================================
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      # Ruff linter with auto-fix
      - id: ruff
        args: [--fix]
        files: ^(dataframe_expectations|tests)/.*\.py$
        stages: [commit, manual]

      # Ruff formatter (replaces black)
      - id: ruff-format
        files: ^(dataframe_expectations|tests)/.*\.py$
        stages: [commit, manual]

  # ============================================================================
  # Type checking - mypy
  # ============================================================================
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: ^dataframe_expectations/.*\.py$
        args: [--config-file, ./pyproject.toml]
        additional_dependencies: [
          types-tabulate,
          pandas-stubs,
          pyspark-stubs,
          types-PyYAML,
        ]
        stages: [commit, manual]
