[project]
name = "dataframe-expectations"
version = "0.1.2"
description = "Python library designed to validate Pandas and PySpark DataFrames using customizable, reusable expectations"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=1.5.0",
    "pyspark>=3.3.0",
    "tabulate>=0.8.9",
]

[dependency-groups]
dev = [
    "numpy>=1.21.0",
    "pytest>=7.0.0",
    "pre-commit>=2.20.0",
    "ruff>=0.1.0",
    "pytest-cov>=4.0.0",
]
docs = [
    "sphinx>=4.0.0",
    "pydata-sphinx-theme>=0.13.0",
    "sphinx-autobuild>=2021.3.14",
    "pyspark>=3.3.0",
    "pandas>=1.5.0",
    "tabulate>=0.8.9",
]


[tool.ruff]
target-version = "py310"  # Target the minimum supported version
line-length = 100

[tool.mypy]
python_version = "3.10"  # Target the minimum supported version
warn_unused_configs = false
disallow_untyped_defs = false
warn_return_any = false
ignore_missing_imports = true
check_untyped_defs = false
