name: CI

on: [push]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}${{ github.ref_name != github.event.repository.default_branch && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"
    steps:
      - uses: actions/checkout@v4
      - name: Install Python and UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          uv sync --group dev
      - name: Run sanity check
        run: |
          cd dataframe_expectations
          uv run python sanity_checks.py
          cd ..
      - name: Run tests
        run: |
          uv run pytest tests/ --cov=dataframe_expectations

  lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"
    steps:
      - uses: actions/checkout@v4
      - name: Install Python and UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          uv sync --group dev
      - name: Pre-commit
        run: |
          uv run pre-commit run --all-files --show-diff-on-failure

  docs:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python and UV
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          uv sync --group docs
      - name: Build docs
        run: |
          cd docs
          uv run sphinx-build source build/html
          cd ..
